title: Illuminate Email Builder
email: ryan@takenot.es
description: This is the Alight Solutions Email Builder SSG. It requires Jekyll, and uses the Acorn grid framework. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#Global Links


# SASS
sass:
    sass_dir: _includes/sass

collections: 
  build:
    output: true
    permalink: /build/:title    
  dist:
    output: true
    permalink: /dist/:title


defaults:
-
  scope:
    path: 
    type: build
  values:
    layout: build
-
  scope:
    path: 
    type: dist
  values:
    layout: dist

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
